language: node_js
node_js:
  - "10"
sudo: true
dist: trusty

branches:
  only:
  - master

script:
  - ng build --base-href "https://ahsanayaz.github.io/marvel-heroes/" --prod

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: dist/marvel-heroes
  on:
    branch: master
